<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */


use App\Http\ApiV1\Modules\Restaurant\Controllers\ReservationController;
use App\Http\ApiV1\Modules\Restaurant\Controllers\RestaurantController;
use Illuminate\Support\Facades\Route;

Route::post('restaurants', [RestaurantController::class, 'create']);
Route::get('restaurants/{id}', [RestaurantController::class, 'get']);
Route::get('restaurants', [RestaurantController::class, 'getAll']);

Route::get('restaurants/{restaurantId}/reservations', [ReservationController::class, 'get']);
Route::post('restaurants/{restaurantId}/reservations', [ReservationController::class, 'create']);
